### PR TITLE
switch to using BinaryBuilder/BinaryProvider

### PR DESCRIPTION
**Pull request by mweastwood**
This should replace #96.

I've tested this locally (Linux x86_64, and things seem to work fine here at least). I believe the additional version bump relative to #96 resolves the issues that were seen there. We're also using more recent versions of BinaryBuilder and BinaryProvider.

Here we are affected by staticfloat/ObjectFile.jl#7 because cfitsio builds a fat macho on OSX, which isn't currently supported by this workflow. I believe recent changes to BinaryBuilder make it possible to work around this problem, but the usual auditing of the binary is not performed.

I have this hosted on my own Github account for now, but it should definitely be transferred to JuliaAstro at some point.

Link to the builder repo: https://github.com/mweastwood/CFITSIOBuilder

### CODE REVIEW

**Comment by mweastwood** [comment]
Hmm, it looks like there is a problem on Windows. I have a Windows PC at home, so I'll be able to take a look within the next week or so (out of town at the moment).

My initial guess is that it is maybe related to this warning that I get during the build process:
```
Warning: lib/libcfitsio.dll should be in `bin`
```

**Comment by mweastwood** [comment]
Alright, perfect. This is now passing on all platforms.

**Comment by mweastwood** [comment]
I have transferred CFITSIOBuilder to JuliaAstro. This is basically ready to be merged now.

**Comment by helgee** [comment]
LGTM

**Comment by mweastwood** [comment]
If there are no objections I'm going to merge this tomorrow.

This will close #49 because we no longer look for the system CFITSIO under any circumstances. On the plus side we have to do infinitely less worrying about all the different possible system configurations, and we know exactly which version of CFITSIO all of our users are using.

**Pull request merged**
