### PR TITLE
Fixes Julia 0.4-rc2 warnings 

### PR DESCRIPTION
**Pull request by jeff-regier**
Hi Kyle, This PR fixes all the deprecated warnings from FITSIO.jl caused by the recent changes to Julia 0.4.

### CODE REVIEW

**Comment by kbarbary** [comment]
Nice! One question: are the `@compat(UInt8)` necessary, or can you just do `UInt8` once `Compat` is used? The later seems to work for me in the REPL.

**Comment by jeff-regier** [comment]
Oh, I see...it works for me too on the command line. I guess I shouldn't
have put @compat everywhere.

**Comment by jeff-regier** [comment]
I've now removed the unnecessary calls to `@compat`.

**Comment by kbarbary** [comment]
Thanks!

**Pull request merged**
