### PR TITLE
Support memory backed files

### PR DESCRIPTION
**Pull request by Keno**
Support read-only memory backed files via `ffomem`. Also clean up a couple of deprecations
while I'm here.

### CODE REVIEW

**Comment by kbarbary** [comment]
Thanks! Need a new tagged release for Celeste? Otherwise, will probably wait until 0.6 is out and more deprecation cleanups are done here.

**Comment by Keno** [comment]
No, I think we're ok. This is an option only, so not required to run something.

**Comment by giordano** [comment]
@Keno Should `hidden` have a parameter type `T` and the type `FITS` be parametrized by `T`, rather than having a [field with abstract type](https://docs.julialang.org/en/latest/manual/performance-tips.html#Avoid-fields-with-abstract-type-1)?

**Comment by Keno** [comment]
No, `hidden` is never read, so its type doesn't matter. It's just there to give the GC and edge to the underlying memory to prevent it from being freed.

**Comment by giordano** [comment]
I see, thanks for the explanation.

**Pull request merged**
