### PR TITLE
Switch to CFITSIO.jl

### PR DESCRIPTION
**Pull request by mileslucas**

### CODE REVIEW

**Comment by mileslucas** [comment]
drone errors are due to lack of Julia 1.4 image

**Comment by giordano** [comment]
Yeah, I know... :disappointed: Julia 1.3 might work for 32-bit arm though

**Comment by mileslucas** [comment]
What still needs to be done for this?

**Comment by mileslucas** [comment]
@giordano oops, I think I needed to remove the `deps` folder. `build.jl` is being executed on a fresh install and failing because `BinaryProvider` isn't in the Project.toml. We shouldn't need the build script at all right? Testing locally right now.

**Comment by giordano** [comment]
Uh, yeah, my bad that didn't notice, but weird that this wasn't caught by CI :confused:

**Comment by mileslucas** [comment]
[it looks like it was "caught" by CI](https://travis-ci.org/github/JuliaAstro/FITSIO.jl/jobs/714256018#L251), it just didn't break any of the tests because we didn't need any of the products from the build script. As it stands, this is just an installation inconvenience- I can confirm that even with the error FITSIO loads and works fine.

**Comment by giordano** [comment]
I see.

**Pull request merged**
