### PR TITLE
Fix v0.4 deprecation warnings

### PR DESCRIPTION
**Pull request by kbarbary**
This depends on #22. I'll rebase this once we merge that PR. The first two commits are in #22; only the last commit here, 2dc0f5f, is new. Just look at that.

### CODE REVIEW

**Comment by kbarbary** [comment]
There seem to be no comments on this or #22, so I'm going to go ahead and just merge both here.

**Comment by nirinA** [comment]
sorry for the late comment.
there are also depreciation warning in `hdutype.jl` with `parseint` and `parsefloat`?

**Comment by kbarbary** [comment]
I didn't see warnings on Julia master built last week, but maybe I missed them. Will have another look.

**Comment by nirinA** [comment]
with:
```
julia> versioninfo()
Julia Version 0.4.0-dev+3889
Commit 271bc23* (2015-03-18 20:37 UTC)
Platform Info:
  System: Linux (x86_64-slackware-linux)
  CPU: Intel(R) Celeron(R) CPU G1610 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
i get:
```
julia> readheader(sed[1])
WARNING: parseint(s) is deprecated, use parse(Int,s) instead.
 in depwarn at ./deprecated.jl:40
 in parseint at deprecated.jl:29
 in parse_header_val at /home/nirina/.julia/v0.4/FITSIO/src/hdutypes.jl:153
 in readheader at /home/nirina/.julia/v0.4/FITSIO/src/hdutypes.jl:203
WARNING: parsefloat(s::AbstractString) is deprecated, use parse(Float64,s) instead.
 in depwarn at ./deprecated.jl:40
 in parsefloat at deprecated.jl:29
 in parse_header_val at /home/nirina/.julia/v0.4/FITSIO/src/hdutypes.jl:156
 in readheader at /home/nirina/.julia/v0.4/FITSIO/src/hdutypes.jl:203
```

**Comment by kbarbary** [comment]
Ah, I must have missed it. The new syntax was just added to Compat 4 days ago: https://github.com/JuliaLang/Compat.jl/commit/cafb9f0befc34654709506f5cf00cc6fa8b77328

We should just be able to change these to `@Compat parse(T, s)` and require Compat>=v"0.3.4"

I can do it or if you want to do a quick PR, that would be great.

**Comment by nirinA** [comment]
i may not have the time to work on it, and the other issue on WCSLIB i just submitted, until next week, so please do!

**Comment by kbarbary** [comment]
Fixed in aad77c1.

**Pull request merged**
